"""initial: 4 core tables

Revision ID: 95c26251cd7b
Revises: 
Create Date: 2026-07-07 02:59:44.965525
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '95c26251cd7b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_update_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('task_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('missing_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('error_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_update_task_status_started', 'data_update_task', ['status', 'started_at'], unique=False)
    op.create_index('ix_data_update_task_type_started', 'data_update_task', ['task_type', 'started_at'], unique=False)
    op.create_index('uq_data_update_task_type_key', 'data_update_task', ['task_type', 'task_key'], unique=True, postgresql_where='task_key IS NOT NULL')
    op.create_table('k_line_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open_raw', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high_raw', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low_raw', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close_raw', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('preclose_raw', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('open_qfq', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high_qfq', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low_qfq', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close_qfq', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('preclose_qfq', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('open_hfq', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high_hfq', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low_hfq', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close_hfq', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('preclose_hfq', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('turn', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pct_chg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('trade_status', sa.SmallInteger(), nullable=False),
    sa.Column('is_st_row', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', name='uq_k_line_daily_code_date')
    )
    op.create_index('ix_k_line_daily_code_date_desc', 'k_line_daily', ['ts_code', 'trade_date'], unique=False)
    op.create_index('ix_k_line_daily_date_code', 'k_line_daily', ['trade_date', 'ts_code'], unique=False)
    op.create_table('stock_basic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('bs_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('delist_date', sa.Date(), nullable=True),
    sa.Column('is_bj', sa.Boolean(), nullable=False),
    sa.Column('is_common', sa.Boolean(), nullable=False),
    sa.Column('is_st', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bs_code'),
    sa.UniqueConstraint('ts_code')
    )
    op.create_table('trade_calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cal_date', sa.Date(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cal_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_calendar')
    op.drop_table('stock_basic')
    op.drop_index('ix_k_line_daily_date_code', table_name='k_line_daily')
    op.drop_index('ix_k_line_daily_code_date_desc', table_name='k_line_daily')
    op.drop_table('k_line_daily')
    op.drop_index('uq_data_update_task_type_key', table_name='data_update_task', postgresql_where='task_key IS NOT NULL')
    op.drop_index('ix_data_update_task_type_started', table_name='data_update_task')
    op.drop_index('ix_data_update_task_status_started', table_name='data_update_task')
    op.drop_table('data_update_task')
    # ### end Alembic commands ###
