"""add latest_market_cap

Revision ID: 00d6b7a56285
Revises: 95c26251cd7b
Create Date: 2026-07-07 03:29:10.390012
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '00d6b7a56285'
down_revision: str | Sequence[str] | None = '95c26251cd7b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latest_market_cap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('total_market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('circ_market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('market_cap_source', sa.String(length=32), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('latest_market_cap')
    # ### end Alembic commands ###
