"""market cap from baostock synth

Revision ID: 0b5d6b31a977
Revises: 00d6b7a56285
Create Date: 2026-07-07 04:36:04.049087
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '0b5d6b31a977'
down_revision: str | Sequence[str] | None = '00d6b7a56285'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('latest_market_cap', sa.Column('total_share', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('latest_market_cap', sa.Column('liqa_share', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('latest_market_cap', sa.Column('snapshot_close', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('latest_market_cap', sa.Column('snapshot_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('latest_market_cap', 'snapshot_date')
    op.drop_column('latest_market_cap', 'snapshot_close')
    op.drop_column('latest_market_cap', 'liqa_share')
    op.drop_column('latest_market_cap', 'total_share')
    # ### end Alembic commands ###
